### ISSUE TITLE
difference between windowSize=5 and windowSize=25

### ISSUE THREAD

**Issue by ainArindom** [gokriznastic/HybridSN#2]
Why you have taken different windowSize=5 in function createImageCubes() and windowSize=25. What is the difference it would make in program. I am new to this field. please explain..

**Comment by gokriznastic** [comment]
windowSize=5 in the creatImageCubes() method is the default value of spatial dimensions of the image cube i.e. in the case where no windowSize is specified in the function call.

**Comment by ainArindom** [comment]
Thank u for ur ans. But I want to know why two different windowSize is taken

**Comment by gokriznastic** [comment]
It is not that 2 different windowSize is taken. It's just that I may have not changed the default value of 5 as it can be explicitly specified in the function call.
